import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Test App",
  description: "Generated by Coding Hustler",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='{inter.className} w-full h-full'>
        <nav className="w-1/2 h-[50px] flex justify-center items-center mt-1 mx-auto border rounded-xl bg-slate-500">
          <div className="flex justify-between">
            <Link className="m-2 p-2 transition-all border rounded-lg font-bold bg-white hover:bg-sky-300 hover:rounded-xl"
              href='/'>
              Home
            </Link>
            <Link className="m-2 p-2 transition-all border rounded-lg font-bold bg-white hover:bg-sky-300 hover:rounded-xl"
              href='/posts'>
              Posts
            </Link>
            <Link className="m-2 p-2 transition-all border rounded-lg font-bold bg-white hover:bg-sky-300 hover:rounded-xl"
              href='/articals'>
              Articals
            </Link>
            <Link className="m-2 p-2 transition-all border rounded-lg font-bold bg-white hover:bg-sky-300 hover:rounded-xl"
              href='/posts/newlink'>
              New Link
            </Link>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
